export const tags = ["All", "Frontend", "Backend", "Fullstack", "DevOps", "Design"];

export const jobs = [
  {
    id: 1,
    title: "Frontend Developer",
    company: "TechNova",
    location: "Remote",
    type: "Full Time",
    tag: "Frontend",
    salary: "5-6LPA",
  },
  {
    id: 2,
    title: "Backend Engineer",
    company: "DataCore",
    location: "Bangalore",
    type: "Remote",
    tag: "Backend",
    salary: "5-6LPA",
  },
  {
    id: 3,
    title: "UI/UX Designer",
    company: "PixelCraft",
    location: "Mumbai",
    type: "Hybrid",
    tag: "Design",
    salary: "5-6LPA",
  },
  {
    id: 4,
    title: "Full Stack Developer",
    company: "Meta",
    location: "London",
    type: "Hybrid",
    tag: "Fullstack",
    salary: "50-60LPA",
  },
  {
    id: 5,
    title: "DevOps Engineer",
    company: "PixelCraft",
    location: "Mumbai",
    type: "Hybrid",
    tag: "DevOps",
    salary: "5-6LPA",
  },
  {
    id: 6,
    title: "Full Stack Developer",
    company: "PixelCraft",
    location: "Mumbai",
    type: "Hybrid",
    tag: "Fullstack",
    salary: "5-6LPA",
  },
  {
    id: 7,
    title: "Java Backend",
    company: "PixelCraft",
    location: "Mumbai",
    type: "Hybrid",
    tag: "Backend",
    salary: "5-6LPA",
  },
  // Add more jobs...
];

export const jobsHome = [
  {
    id: 1,
    title: "Frontend Developer",
    company: "TechNova",
    location: "Remote",
    type: "Full Time",
    tag: "Frontend",
    salary: "5-6LPA",
  },
  {
    id: 2,
    title: "Backend Engineer",
    company: "DataCore",
    location: "Bangalore",
    type: "Remote",
    tag: "Backend",
    salary: "5-6LPA",
  },
  {
    id: 3,
    title: "UI/UX Designer",
    company: "PixelCraft",
    location: "Mumbai",
    type: "Hybrid",
    tag: "Design",
    salary: "5-6LPA",
  },
  {
    id: 4,
    title: "Full Stack Developer",
    company: "Meta",
    location: "London",
    type: "Hybrid",
    tag: "Fullstack",
    salary: "50-60LPA",
  },
  {
    id: 5,
    title: "DevOps Engineer",
    company: "PixelCraft",
    location: "Mumbai",
    type: "Hybrid",
    tag: "DevOps",
    salary: "5-6LPA",
  },
  {
    id: 6,
    title: "Full Stack Developer",
    company: "PixelCraft",
    location: "Mumbai",
    type: "Hybrid",
    tag: "Fullstack",
    salary: "5-6LPA",
  }
];